[package]
name = "with"
version = "0.0.0"
edition = "2021"
authors = ["m1m1sha"]

[dependencies]


[workspace]
members = ["crates/packet", "crates/tun"]

[workspace.dependencies]
byteorder = "^1"
tracing = "^0.1"
tracing-subscriber = "^0.3"
thiserror = "^1"
windows = "^0.54"
libloading = "^0.8"
encoding = "^0.2"
