language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - RUSTFLAGS='-D warnings' cargo build --verbose --all
  - RUSTFLAGS='-D warnings' cargo test --verbose --all
stages:
  - Check
  - Test
jobs:
  include:
    - stage: Check
      name: Format
      script:
        - rustup component add rustfmt
        - cargo fmt --all -- --check
    - stage: Check
      name: Clippy
      script:
        - rustup component add clippy
        - RUSTFLAGS='-F warnings' cargo clippy --all --tests
