[package]
name = "utils"
version = "0.0.0"
edition = "2021"

[dependencies]
parking_lot = { workspace = true }
tracing = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = [
    "Win32_System_Threading",
    "Win32_Security",
] }
